export const characters = [
    {id:1, image_icon:'jade_icon.jpg', image_large:'jade_large.webp'},
    {id:2, image_icon:'havik_icon.jpeg', image_large:'havik_large.webp'},
    {id:3, image_icon:'sub_zero_icon.jpeg', image_large:'sub_zero_large.png'},
    {id:4, image_icon:'kotal_kahn_icon.png', image_large:'kotal_kahn_large.webp'},
    {id:5, image_icon:'raiden_icon.jpg', image_large:'raiden_large.png'},
    {id:6, image_icon:'kung_lao_icon.jpeg', image_large:'kung_lao_large.webp'},
    {id:7, image_icon:'rain_icon.jpeg', image_large:'rain_large.png'},
    {id:8, image_icon:'shao_khan_icon.jpg', image_large:'shao_kahn_large.webp'},
    {id:9, image_icon:'shang_tsung_icon.webp', image_large:'shang_tsung_large.png'},
    {id:10, image_icon:'sonya_blade_icon.jpg', image_large:'sonya_blade_large.png'},
    {id:11, image_icon:'scorpion_icon.jpg', image_large:'scorpion_large.png'},
    {id:12, image_icon:'baraka_icon.png', image_large:'baraka_large.webp'},
    {id:13, image_icon:'mileena_icon.jpg', image_large:'mileena_large.png'},
    {id:14, image_icon:'ermac_icon.webp', image_large:'ermac_large.png'},
    {id:15, image_icon:'sindel_icon.webp', image_large:'sindel_large.webp'},
]